# Generated by Django 3.2.15 on 2022-09-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
