# Generated by Django 3.2.15 on 2022-09-17 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide', '0003_alter_patron_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patron',
            name='id',
        ),
        migrations.AlterField(
            model_name='patron',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
