# Generated by Django 3.2.15 on 2022-09-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_alter_patron_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
