# Generated by Django 3.2.15 on 2022-09-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
