# Generated by Django 3.2.15 on 2022-09-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('account_issues', 'request help with your account'), ('submission_request', 'writing for us'), ('correction_request', 'correct one of our location listings'), ('location_request', 'suggest an location for us to visit'), ('non_cateorized', 'other purposes')], max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
