# Generated by Django 3.2.15 on 2022-09-17 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0002_patronupgrade_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patronupgrade',
            name='country_of_residence',
        ),
        migrations.AddField(
            model_name='patronupgrade',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to=settings.AUTH_USER_MODEL),
        ),
    ]
