# Generated by Django 3.2.15 on 2022-09-17 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0003_auto_20220917_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patronupgrade',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to=settings.AUTH_USER_MODEL),
        ),
    ]
